package org.eclipselabs.spray.generator.graphiti.templates;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ObjectExtensions;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.eclipse.xtext.xtend2.lib.StringConcatenation;
import org.eclipselabs.spray.generator.graphiti.templates.FileGenerator;
import org.eclipselabs.spray.generator.graphiti.templates.JavaGenFile;
import org.eclipselabs.spray.generator.graphiti.util.GeneratorUtil;
import org.eclipselabs.spray.generator.graphiti.util.MetaModel;
import org.eclipselabs.spray.mm.spray.Diagram;
import org.eclipselabs.spray.mm.spray.MetaClass;
import org.eclipselabs.spray.mm.spray.MetaReference;
import org.eclipselabs.spray.mm.spray.extensions.SprayExtensions;

@SuppressWarnings("all")
public class DeleteReferenceFeature extends FileGenerator {
  
  @Inject
  private SprayExtensions e1;
  
  public StringConcatenation generateBaseFile(final EObject modelElement) {
    JavaGenFile _javaGenFile = this.getJavaGenFile();
    String _baseClassName = _javaGenFile.getBaseClassName();
    StringConcatenation _mainFile = this.mainFile(((MetaReference) modelElement), _baseClassName);
    return _mainFile;
  }
  
  public StringConcatenation generateExtensionFile(final EObject modelElement) {
    JavaGenFile _javaGenFile = this.getJavaGenFile();
    String _className = _javaGenFile.getClassName();
    StringConcatenation _mainExtensionPointFile = this.mainExtensionPointFile(((MetaReference) modelElement), _className);
    return _mainExtensionPointFile;
  }
  
  public StringConcatenation mainExtensionPointFile(final MetaReference metaReference, final String className) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _extensionHeader = this.extensionHeader(this);
    _builder.append(_extensionHeader, "");
    _builder.newLineIfNotEmpty();
    _builder.append("package ");
    String _feature_package = GeneratorUtil.feature_package();
    _builder.append(_feature_package, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.features.IFeatureProvider;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(className, "");
    _builder.append(" extends ");
    _builder.append(className, "");
    _builder.append("Base {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(className, "    ");
    _builder.append("(IFeatureProvider fp) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("super(fp);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public StringConcatenation mainFile(final MetaReference reference, final String className) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = this.e1.getName(reference);
    final String referenceName = _name;
    _builder.newLineIfNotEmpty();
    MetaClass _metaClass = reference.getMetaClass();
    EClass _type = _metaClass.getType();
    EList<EReference> _eAllReferences = _type.getEAllReferences();
    final Function1<EReference,Boolean> _function = new Function1<EReference,Boolean>() {
        public Boolean apply(final EReference e) {
          String _name_1 = e.getName();
          boolean _operator_equals = ObjectExtensions.operator_equals(_name_1, referenceName);
          return ((Boolean)_operator_equals);
        }
      };
    EReference _findFirst = IterableExtensions.<EReference>findFirst(_eAllReferences, _function);
    EReference target = _findFirst;
    _builder.append(" ");
    _builder.newLineIfNotEmpty();
    MetaClass _metaClass_1 = reference.getMetaClass();
    Diagram _diagram = _metaClass_1.getDiagram();
    String _name_2 = _diagram.getName();
    String diagramName = _name_2;
    _builder.newLineIfNotEmpty();
    MetaClass _metaClass_2 = reference.getMetaClass();
    EClass _type_1 = _metaClass_2.getType();
    String _fullPackageName = MetaModel.fullPackageName(_type_1);
    String fullPackage = _fullPackageName;
    _builder.newLineIfNotEmpty();
    EClass _eReferenceType = target.getEReferenceType();
    String _fullPackageName_1 = MetaModel.fullPackageName(_eReferenceType);
    String fullReferencePackage = _fullPackageName_1;
    _builder.newLineIfNotEmpty();
    StringConcatenation _header = this.header(this);
    _builder.append(_header, "");
    _builder.newLineIfNotEmpty();
    _builder.append("/*******************************************************************************");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* <copyright>");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* </copyright>");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*******************************************************************************/");
    _builder.newLine();
    _builder.append("package ");
    String _feature_package = GeneratorUtil.feature_package();
    _builder.append(_feature_package, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import ");
    _builder.append(fullPackage, "");
    _builder.append(".");
    MetaClass _metaClass_3 = reference.getMetaClass();
    String _name_3 = this.e1.getName(_metaClass_3);
    _builder.append(_name_3, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    _builder.append(fullReferencePackage, "");
    _builder.append(".");
    EClass _eReferenceType_1 = target.getEReferenceType();
    String _name_4 = _eReferenceType_1.getName();
    _builder.append(_name_4, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import org.eclipse.emf.ecore.EObject;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.ecore.util.EcoreUtil;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.features.IFeatureProvider;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.features.IRemoveFeature;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.features.context.IDeleteContext;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.features.context.IRemoveContext;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.features.context.impl.RemoveContext;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.mm.pictograms.AnchorContainer;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.mm.pictograms.Connection;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.mm.pictograms.PictogramElement;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.services.Graphiti;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.ui.features.DefaultDeleteFeature;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.util.IPredefinedRenderingStyle;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.services.Graphiti;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.ui.features.DefaultDeleteFeature;");
    _builder.newLine();
    _builder.append("import org.eclipse.graphiti.ui.features.DefaultFeatureProvider;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(className, "");
    _builder.append(" extends DefaultDeleteFeature {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public ");
    _builder.append(className, "    ");
    _builder.append("(IFeatureProvider fp) {");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("super(fp);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// TODO Auto-generated constructor stub");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/*");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* (non-Javadoc)");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* ");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @see");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* org.eclipse.graphiti.features.IDeleteFeature#delete(org.eclipse.graphiti.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* features.context.IDeleteContext)");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void delete(IDeleteContext context) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("PictogramElement pe = context.getPictogramElement();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String reference = Graphiti.getPeService().getPropertyValue(pe, \"REFERENCE\");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String element   = Graphiti.getPeService().getPropertyValue(pe, \"TARGETOBJECT\");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Object[] businessObjectsForPictogramElement = getAllBusinessObjectsForPictogramElement(pe);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (businessObjectsForPictogramElement != null && businessObjectsForPictogramElement.length > 0) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (!getUserDecision()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("return;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("preDelete(context);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// TRY");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if( pe instanceof Connection) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Connection line = (Connection)pe;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("AnchorContainer parent = line.getStart().getParent();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Object start = getBusinessObjectForPictogramElement(parent);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("AnchorContainer child = line.getEnd().getParent();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Object end = getBusinessObjectForPictogramElement(child);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("//END TRY");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("IRemoveContext rc = new RemoveContext(pe);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("IFeatureProvider featureProvider = getFeatureProvider();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("IRemoveFeature removeFeature = featureProvider.getRemoveFeature(rc);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (removeFeature != null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("removeFeature.remove(rc);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("deleteReferences(businessObjectsForPictogramElement, reference, element);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("postDelete(context);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* Delete business objects.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* ");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @param businessObjects");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*            the business objects");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected void deleteReferences(Object[] businessObjects, String reference, String element) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (businessObjects != null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("for (Object bo : businessObjects) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("deleteReference(bo, reference, element);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* Delete business object.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* ");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* @param bo");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*            the bo");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected void deleteReference(Object bo, String reference, String element) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (bo instanceof EObject) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if( reference == null){");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("EcoreUtil.delete((EObject) bo, true);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("if( bo instanceof ");
    MetaClass _metaClass_4 = reference.getMetaClass();
    String _name_5 = this.e1.getName(_metaClass_4);
    _builder.append(_name_5, "                ");
    _builder.append(" ){");
    _builder.newLineIfNotEmpty();
    _builder.append("                    ");
    MetaClass _metaClass_5 = reference.getMetaClass();
    String _name_6 = this.e1.getName(_metaClass_5);
    _builder.append(_name_6, "                    ");
    _builder.append(" object = (");
    MetaClass _metaClass_6 = reference.getMetaClass();
    String _name_7 = this.e1.getName(_metaClass_6);
    _builder.append(_name_7, "                    ");
    _builder.append(" ) bo;");
    _builder.newLineIfNotEmpty();
    _builder.append("                    ");
    _builder.newLine();
    {
      int _upperBound = target.getUpperBound();
      boolean _operator_notEquals = ObjectExtensions.operator_notEquals(((Integer)_upperBound), ((Integer)1));
      if (_operator_notEquals) {
        _builder.append("            ");
        EClass _eReferenceType_2 = target.getEReferenceType();
        String _name_8 = _eReferenceType_2.getName();
        _builder.append(_name_8, "            ");
        _builder.append(" toBeRemoved = null;");
        _builder.newLineIfNotEmpty();
        _builder.append("            ");
        _builder.append("for (");
        EClass _eReferenceType_3 = target.getEReferenceType();
        String _name_9 = _eReferenceType_3.getName();
        _builder.append(_name_9, "            ");
        _builder.append(" rule : object.get");
        String _name_10 = target.getName();
        String _firstUpper = StringExtensions.toFirstUpper(_name_10);
        _builder.append(_firstUpper, "            ");
        _builder.append("()) {");
        _builder.newLineIfNotEmpty();
        _builder.append("            ");
        _builder.append("    ");
        _builder.append("if( rule.getName().equals(element)){");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("        ");
        _builder.append("toBeRemoved = rule;");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("    ");
        _builder.append("}");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("}    ");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("if( toBeRemoved != null ){");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("    ");
        _builder.append("object.get");
        String _name_11 = target.getName();
        String _firstUpper_1 = StringExtensions.toFirstUpper(_name_11);
        _builder.append(_firstUpper_1, "                ");
        _builder.append("().remove(toBeRemoved);");
        _builder.newLineIfNotEmpty();
        _builder.append("            ");
        _builder.append("    ");
        _builder.append("// TODO Must remove toBeRemoved if it is a containment reference !");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("}");
        _builder.newLine();} else {
        _builder.append("            ");
        _builder.append("object.set");
        String _firstUpper_2 = StringExtensions.toFirstUpper(referenceName);
        _builder.append(_firstUpper_2, "            ");
        _builder.append("(null);");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("                ");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("System.out.println(\"DELETE OBJECT \" + bo);");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}