/*
 * generated by Xtext
 */
package org.eclipselabs.spray.generator.graphiti

import com.google.inject.Inject
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IFileSystemAccess
import org.eclipse.xtext.generator.IGenerator

class SprayGenerator implements IGenerator {
	@Inject
	SprayGraphitiGenerator graphitiGenerator

	override void doGenerate(Resource resource, IFileSystemAccess fsa) {  
		graphitiGenerator.doGenerate(resource, fsa)
	}


}
