/*
 * generated by Xtext
 */
package org.xspray.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.model.TokenTypeToStringMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.xspray.xtext.ui.syntaxcoloring.XsprayHighlightingConfiguration;
import org.xspray.xtext.ui.syntaxcoloring.XsprayTokenToAttributeIdMapper;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XsprayUiModule extends org.xspray.xtext.ui.AbstractXsprayUiModule {
    public XsprayUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
    
    public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
        return XsprayTokenToAttributeIdMapper.class ;
    }

    @Override
    public void configure(Binder binder) {
        super.configure(binder);
        binder.bind(TokenTypeToStringMapper.class).to(XsprayTokenToAttributeIdMapper.class);
        binder.bind(IHighlightingConfiguration.class).to(XsprayHighlightingConfiguration.class);
    }


    
}
