/*************************************************************************************
 *
 * Generated by Spray DiagramTypeProvider.xtend
 * 
 * This file is an extension point: copy to "src" folder to manually add code to this
 * extension point.
 *
 *************************************************************************************/
package org.eclipselabs.spray.examples.mod4j.diagram;

public class Mod4jDiagramTypeProvider extends Mod4jDiagramTypeProviderBase {

}
