/*
 * generated by Xtext
 */
package org.xspray.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XsprayRuntimeModule extends org.xspray.xtext.AbstractXsprayRuntimeModule {

}
