/*
 * generated by Xtext
 */
package org.xspray.xtext;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.xspray.xtext.customizing.XsprayQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XsprayRuntimeModule extends org.xspray.xtext.AbstractXsprayRuntimeModule {
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return XsprayQualifiedNameProvider.class;
	}
}
