/*
* generated by Xtext
*/
package org.xspray.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xspray.xtext.services.XsprayGrammarAccess;

public class XsprayParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XsprayGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xspray.xtext.parser.antlr.internal.InternalXsprayParser createParser(XtextTokenStream stream) {
		return new org.xspray.xtext.parser.antlr.internal.InternalXsprayParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Diagram";
	}
	
	public XsprayGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XsprayGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
