/*
 * generated by Xtext
 */
package org.xspray.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XsprayExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.xspray.xtext.ui.internal.XsprayActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.xspray.xtext.ui.internal.XsprayActivator.getInstance().getInjector("org.xspray.xtext.Xspray");
	}
	
}
