/*
* generated by Xtext
*/
package org.xspray.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XsprayUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xspray.xtext.ui.internal.XsprayActivator.getInstance().getInjector("org.xspray.xtext.Xspray");
	}
	
}
